import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { db } from "../data/db";
import { createHouseholdAdminItem } from "../data/repositories";
import { seedInitialDataIfNeeded } from "../data/repositories/appRepository";
import type { ExportEnvelope } from "../types/importExport";
import { createExportPayload, getLocalDataSummary, parseImportJson, resetLocalDataAndReseed, restoreFromImport, validateImportPayload } from "./importExportService";

describe("local backup and restore", () => {
  let valid: ExportEnvelope;
  beforeEach(async () => {
    await db.delete(); await db.open(); await seedInitialDataIfNeeded();
    const now = new Date().toISOString();
    await db.events.add({ id: "event_test", title: "Seb swimming", category: "lesson", status: "confirmed", startAt: "2026-06-22T16:00:00.000Z", endAt: "2026-06-22T17:00:00.000Z", allDay: false, participants: ["member_seb"], responsibleAdults: ["member_phil"], prepTasks: [{ id: "prep_test", title: "Pack kit", ownerIds: ["member_phil"], priority: "normal", status: "open", blocksEvent: false, createdAt: now, updatedAt: now }], resourceNeeds: [{ id: "need_test", resourceId: "resource_family_car", needStatus: "required", createdAt: now, updatedAt: now }], templateId: "template_swimming_lesson", createdAt: now, updatedAt: now });
    await createHouseholdAdminItem({ title: "Boiler service", category: "home_maintenance", adminType: "boiler_service", status: "active", dueDate: "2026-07-01", renewalCycle: "annual", ownerMemberId: "member_phil", reminderDaysBefore: [30, 14, 7] });
    valid = await createExportPayload();
  });
  afterEach(async () => { await db.delete(); });

  it("exports every persistent store with Officially Organised metadata and counts", () => {
    expect(valid.schema).toBe("officially-organised-data-v5");
    expect(valid.sourceAppName).toBe("Officially Organised");
    expect(valid.exportedAt).toMatch(/^\d{4}-/);
    expect(Object.keys(valid.data)).toEqual(expect.arrayContaining(["events", "eventSeries", "celebrationOccasions", "giftPlans", "householdAdminItems", "schoolCalendars", "countdownTargets", "auditLog"]));
    expect(valid.recordCounts.events).toBe(1);
    expect(() => JSON.parse(JSON.stringify(valid))).not.toThrow();
    expect(valid.data).not.toHaveProperty("conflicts");
  });

  it("rejects invalid JSON and unsupported envelopes", () => {
    expect(parseImportJson("{" )).toMatchObject({ ok: false });
    expect(validateImportPayload({}).errors.map((x) => x.code)).toContain("unsupported_schema");
    expect(validateImportPayload({ ...valid, schemaVersion: 99 }).valid).toBe(false);
    expect(validateImportPayload({ ...valid, data: { ...valid.data, events: {} } }).errors.map((x) => x.code)).toContain("store_not_array");
  });

  it("accepts an export generated by the current app", () => expect(validateImportPayload(valid).valid).toBe(true));

  it.each([
    ["duplicate event IDs", (p: ExportEnvelope) => p.data.events.push(structuredClone(p.data.events[0])), "duplicate_id"],
    ["duplicate member IDs", (p: ExportEnvelope) => p.data.familyMembers.push(structuredClone(p.data.familyMembers[0])), "duplicate_id"],
    ["missing participant", (p: ExportEnvelope) => p.data.events[0].participants = ["missing"], "missing_participant"],
    ["missing responsible adult", (p: ExportEnvelope) => p.data.events[0].responsibleAdults = ["missing"], "missing_responsible_adult"],
    ["missing place", (p: ExportEnvelope) => p.data.events[0].placeId = "missing", "missing_place_reference"],
    ["missing resource", (p: ExportEnvelope) => p.data.events[0].resourceNeeds[0].resourceId = "missing", "missing_resource_reference"],
    ["missing prep owner", (p: ExportEnvelope) => p.data.events[0].prepTasks[0].ownerIds = ["missing"], "missing_prep_owner"],
    ["bad event ordering", (p: ExportEnvelope) => p.data.events[0].endAt = p.data.events[0].startAt, "invalid_event_order"],
    ["unknown category", (p: ExportEnvelope) => { (p.data.events[0] as { category: string }).category = "mystery"; }, "unknown_category"],
    ["broken series", (p: ExportEnvelope) => p.data.events[0].seriesId = "missing", "missing_series_reference"],
    ["bad school dates", (p: ExportEnvelope) => p.data.schoolCalendars[0].periods[0].startDate = "2026-99-40", "invalid_school_period"],
    ["bad countdown date", (p: ExportEnvelope) => p.data.countdownTargets[0].targetDate = "not-a-date", "invalid_countdown_date"],
    ["bad household admin enum", (p: ExportEnvelope) => { (p.data.householdAdminItems[0] as { category: string }).category = "mystery"; }, "invalid_household_admin_category"],
  ])("rejects %s with a readable issue", (_name, mutate, code) => {
    const payload = structuredClone(valid); mutate(payload);
    const result = validateImportPayload(payload);
    expect(result.valid).toBe(false); expect(result.errors.some((x) => x.code === code && x.message.startsWith("Import blocked."))).toBe(true);
  });

  it("round trips representative local data and replaces later changes", async () => {
    await db.events.add({ ...valid.data.events[0], id: "event_later", title: "Not in backup" });
    await restoreFromImport(valid);
    expect(await db.events.get("event_later")).toBeUndefined();
    expect((await db.events.get("event_test"))?.title).toBe("Seb swimming");
    expect(await getLocalDataSummary()).toMatchObject({ ...valid.recordCounts, auditLog: valid.recordCounts.auditLog + 1 });
  });

  it("blocks invalid restore without changing live data", async () => {
    const broken = structuredClone(valid); broken.data.events[0].participants = ["missing"];
    await expect(restoreFromImport(broken)).rejects.toThrow("Import blocked");
    expect(await db.events.get("event_test")).toBeDefined();
  });

  it("reset clears user data and reseeds baseline records without duplicates", async () => {
    await resetLocalDataAndReseed(); await resetLocalDataAndReseed();
    expect(await db.events.count()).toBe(0); expect(await db.familyMembers.count()).toBe(4); expect(await db.schoolCalendars.count()).toBe(1); expect(await db.countdownTargets.count()).toBe(2);
  });

  it("exports, restores and validates celebrations and gift plans", async () => {
    const timestamp = new Date().toISOString();
    await db.celebrationOccasions.add({ id: "celebration_test", householdId: "household_lawrence", title: "Party", occasionType: "birthday_party", date: "2026-07-05", recurrence: "none", ownerAdultIds: ["member_phil"], status: "planned", createdAt: timestamp, updatedAt: timestamp });
    await db.giftPlans.add({ id: "gift_test", celebrationId: "celebration_test", recipientName: "Alex", responsibleAdultId: "member_phil", giftStatus: "to_buy", cardStatus: "to_buy", rsvpStatus: "to_reply", linkedPrepTaskIds: [], archived: false, createdAt: timestamp, updatedAt: timestamp });
    const payload = await createExportPayload();
    expect(payload.recordCounts.celebrationOccasions).toBe(1);
    expect(payload.recordCounts.giftPlans).toBe(1);
    await restoreFromImport(payload);
    expect(await db.celebrationOccasions.get("celebration_test")).toBeTruthy();
    expect(await db.giftPlans.get("gift_test")).toBeTruthy();
  });

  it("exports, restores and validates household admin items", async () => {
    await createHouseholdAdminItem({ title: "Boiler service", category: "home_maintenance", adminType: "boiler_service", status: "active", dueDate: "2026-07-01", renewalCycle: "annual", ownerMemberId: "member_phil", reminderDaysBefore: [30, 14, 7] });
    const payload = await createExportPayload();
    expect(payload.recordCounts.householdAdminItems).toBe(2);
    await restoreFromImport(payload);
    expect(await db.householdAdminItems.count()).toBe(2);
  });
});
