import { useState } from "react";
import { Link } from "react-router-dom";
import { ErrorState, LoadingState } from "../components/common/AsyncState";
import { Icon } from "../components/common/Icon";
import { PageHeader } from "../components/layout/PageHeader";
import { deleteSchoolHalfTermConfig, getSchoolCalendar, listSchoolHalfTermConfigs, saveSchoolHalfTermConfig } from "../data/repositories";
import { SCHOOL_ATTIRE_TYPES, SCHOOL_LUNCH_TYPES } from "../domain/constants";
import type { SchoolAttireType, SchoolDayRequirementEntry, SchoolHalfTermConfig, SchoolLunchType } from "../domain/types";
import { useRepositoryQuery } from "../hooks/useRepositoryQuery";
import { ATTIRE_LABELS, createDefaultEntriesForHalfTerm, LUNCH_LABELS, validateSchoolHalfTermConfig } from "../services/schoolReadinessService";
import { formatLongDate } from "../utils/dates";
import { createId } from "../utils/ids";

export function SchoolHalfTermPage() {
  const [version, setVersion] = useState(0); const [draft, setDraft] = useState<SchoolHalfTermConfig>();
  const state = useRepositoryQuery(async () => { const [calendar, configs] = await Promise.all([getSchoolCalendar(), listSchoolHalfTermConfigs()]); return { calendar, configs }; }, [version]);
  const startNew = () => { if (!state.data?.calendar) return; const now = new Date().toISOString(); setDraft({ id: createId("half_term"), schoolCalendarId: state.data.calendar.id, label: "", startDate: "", endDate: "", entries: [], createdAt: now, updatedAt: now }); };
  return <div className="page-stack school-half-term-page"><Link className="back-link back-link--icon" to="/settings/school-calendar"><Icon name="arrowLeft" /> School calendar</Link><PageHeader eyebrow="School readiness" title="Half-term requirements">Load Seb's lunch, uniform, PE and Forest School needs once for each half-term.</PageHeader>
    {state.loading ? <LoadingState /> : null}{state.error ? <ErrorState /> : null}
    {state.data ? <><section className="section-block"><div className="section-heading"><div><p className="eyebrow">Configured periods</p><h2>{state.data.configs.length ? `${state.data.configs.length} half-term configuration${state.data.configs.length === 1 ? "" : "s"}` : "Nothing loaded yet"}</h2></div><button className="button button--primary" onClick={startNew} type="button"><Icon name="plus" /> Add half-term</button></div>{state.data.configs.length ? <div className="school-entry-list">{state.data.configs.map((config) => <article className="school-entry" key={config.id}><div><strong>{config.label}</strong><span>{config.startDate} to {config.endDate} · {config.entries.length} school days</span></div><button onClick={() => setDraft(config)} type="button"><Icon name="edit" /> Edit</button></article>)}</div> : <p className="section-empty-copy">Add the next half-term when the school sends its dates and requirements.</p>}</section>
      {draft ? <HalfTermEditor calendar={state.data.calendar} config={draft} others={state.data.configs} onCancel={() => setDraft(undefined)} onDelete={async () => { await deleteSchoolHalfTermConfig(draft.id); setDraft(undefined); setVersion((v) => v + 1); }} onSave={async (value) => { await saveSchoolHalfTermConfig(value); setDraft(undefined); setVersion((v) => v + 1); }} /> : null}</> : null}
  </div>;
}

function HalfTermEditor({ calendar, config, others, onSave, onCancel, onDelete }: { calendar: Awaited<ReturnType<typeof getSchoolCalendar>>; config: SchoolHalfTermConfig; others: SchoolHalfTermConfig[]; onSave: (value: SchoolHalfTermConfig) => void; onCancel: () => void; onDelete: () => void }) {
  const [value, setValue] = useState(config);
  const rebuild = (next: SchoolHalfTermConfig) => setValue(calendar && next.startDate && next.endDate && next.startDate <= next.endDate ? { ...next, entries: createDefaultEntriesForHalfTerm(next.id, calendar, next.startDate, next.endDate).map((entry) => next.entries.find((old) => old.date === entry.date) ?? entry) } : next);
  const updateEntry = (id: string, patch: Partial<SchoolDayRequirementEntry>) => setValue({ ...value, entries: value.entries.map((entry) => entry.id === id ? { ...entry, ...patch } : entry) });
  const fill = (patch: Partial<SchoolDayRequirementEntry>) => setValue({ ...value, entries: value.entries.map((entry) => ({ ...entry, ...patch })) });
  const validation = validateSchoolHalfTermConfig(value, others);
  return <form className="data-form half-term-editor" onSubmit={(event) => { event.preventDefault(); if (validation.valid) onSave(value); }}><h2>{config.label ? "Edit half-term" : "Add half-term"}</h2><div className="form-grid"><label className="form-field"><span>Label</span><input value={value.label} onChange={(e) => setValue({ ...value, label: e.target.value })} placeholder="e.g. Autumn 1 2026" required /></label><label className="form-field"><span>Source note</span><input value={value.sourceNote ?? ""} onChange={(e) => setValue({ ...value, sourceNote: e.target.value })} placeholder="School email dated…" /></label><label className="form-field"><span>Start date</span><input type="date" value={value.startDate} onChange={(e) => rebuild({ ...value, startDate: e.target.value })} required /></label><label className="form-field"><span>End date</span><input type="date" value={value.endDate} onChange={(e) => rebuild({ ...value, endDate: e.target.value })} required /></label></div>
    {validation.errors.map((error) => <div className="notice notice--error" role="alert" key={error}>{error}</div>)}{validation.warnings.map((warning) => <div className="notice notice--warning" key={warning}>{warning}</div>)}
    {value.entries.length ? <><div className="half-term-bulk" aria-label="Quick fill all open school days"><strong>Quick fill all days</strong><button type="button" onClick={() => fill({ lunchType: "school_dinner" })}>School dinners</button><button type="button" onClick={() => fill({ lunchType: "packed_lunch" })}>Packed lunches</button><button type="button" onClick={() => fill({ attireType: "school_uniform" })}>School uniform</button></div><div className="half-term-days">{value.entries.map((entry) => <DayEditor entry={entry} key={entry.id} onChange={(patch) => updateEntry(entry.id, patch)} />)}</div></> : value.startDate && value.endDate ? <p className="section-empty-copy">There are no open school days in this range.</p> : <p className="section-empty-copy">Choose the first and last date to generate open school-day rows.</p>}
    <div className="form-actions form-actions--spread"><div>{others.some((item) => item.id === config.id) ? <button className="button button--danger" onClick={onDelete} type="button">Delete</button> : null}</div><div className="form-actions"><button className="button button--secondary" onClick={onCancel} type="button">Cancel</button><button className="button button--primary" disabled={!validation.valid || !value.entries.length} type="submit">Save half-term</button></div></div>
  </form>;
}

function DayEditor({ entry, onChange }: { entry: SchoolDayRequirementEntry; onChange: (patch: Partial<SchoolDayRequirementEntry>) => void }) {
  return <fieldset className="half-term-day"><legend>{formatLongDate(entry.date)}</legend><div className="form-grid"><label className="form-field"><span>Lunch</span><select value={entry.lunchType} onChange={(e) => onChange({ lunchType: e.target.value as SchoolLunchType })}>{SCHOOL_LUNCH_TYPES.map((type) => <option value={type} key={type}>{LUNCH_LABELS[type]}</option>)}</select></label><label className="form-field"><span>Dinner choice</span><input value={entry.lunchChoice ?? ""} onChange={(e) => onChange({ lunchChoice: e.target.value })} disabled={entry.lunchType !== "school_dinner"} /></label><label className="form-field"><span>Clothing</span><select value={entry.attireType} onChange={(e) => onChange({ attireType: e.target.value as SchoolAttireType })}>{SCHOOL_ATTIRE_TYPES.map((type) => <option value={type} key={type}>{ATTIRE_LABELS[type]}</option>)}</select></label></div><div className="half-term-checks"><label><input type="checkbox" checked={entry.forestSchool.required} onChange={(e) => onChange({ forestSchool: { ...entry.forestSchool, required: e.target.checked } })} /> Forest School</label>{entry.forestSchool.required ? <><label><input type="checkbox" checked={entry.forestSchool.wellingtonBoots} onChange={(e) => onChange({ forestSchool: { ...entry.forestSchool, wellingtonBoots: e.target.checked } })} /> Wellies</label><label><input type="checkbox" checked={entry.forestSchool.longTrousers} onChange={(e) => onChange({ forestSchool: { ...entry.forestSchool, longTrousers: e.target.checked } })} /> Long trousers</label><label><input type="checkbox" checked={Boolean(entry.forestSchool.waterproofs)} onChange={(e) => onChange({ forestSchool: { ...entry.forestSchool, waterproofs: e.target.checked } })} /> Waterproofs</label></> : null}</div></fieldset>;
}
