import { describe, expect, it } from "vitest";
import type { EventSeries, SchoolCalendar } from "../types";
import { expandSeriesForRange, occurrenceId } from "./seriesService";

const timestamp = "2026-01-01T00:00:00.000Z";
function routine(patch: Partial<EventSeries> = {}): EventSeries { return { id: "series_test", title: "Swimming", category: "lesson", status: "active", recurrence: { frequency: "weekly", dayOfWeek: "monday", startDate: "2026-06-08", endDate: "2026-07-31", startTime: "17:00", durationMinutes: 60 }, defaultParticipants: ["member_seb"], defaultResponsibleAdults: ["member_phil"], defaultResourceNeeds: [{ id: "car", resourceId: "resource_family_car", needStatus: "required", beforeStartMinutes: 15, afterEndMinutes: 15 }], defaultPrepTasks: [{ id: "kit", title: "Pack kit", ownerIds: ["member_phil"], dueOffsetMinutes: -60, priority: "normal", blocksEvent: false }], exceptions: [], createdAt: timestamp, updatedAt: timestamp, ...patch }; }
const calendar: SchoolCalendar = { id: "school", childMemberId: "member_seb", schoolName: "School", academicYearLabel: "2025/26", timezone: "Europe/London", periods: [{ id: "term", label: "Term", type: "term", startDate: "2026-06-01", endDate: "2026-07-20" }, { id: "holiday", label: "Holiday", type: "holiday", startDate: "2026-06-15", endDate: "2026-06-19" }], closureDays: [], createdAt: timestamp, updatedAt: timestamp };

describe("seriesService", () => {
  it("generates weekly occurrences only inside the range and series dates", () => { expect(expandSeriesForRange(routine(), "2026-06-01", "2026-06-30").map((item) => item.occurrenceDate)).toEqual(["2026-06-08", "2026-06-15", "2026-06-22", "2026-06-29"]); expect(expandSeriesForRange(routine(), "2026-08-01", "2026-08-10")).toEqual([]); });
  it("anchors fortnightly recurrence to the first configured weekday from startDate", () => { const item = routine({ recurrence: { ...routine().recurrence, frequency: "fortnightly" } }); expect(expandSeriesForRange(item, "2026-06-01", "2026-07-10").map((event) => event.occurrenceDate)).toEqual(["2026-06-08", "2026-06-22", "2026-07-06"]); });
  it("generates monthly recurrence and skips months without that date", () => { const item = routine({ recurrence: { frequency: "monthly", dayOfMonth: 31, startDate: "2026-01-31", startTime: "09:00", durationMinutes: 30 } }); expect(expandSeriesForRange(item, "2026-03-01", "2026-06-01").map((event) => event.occurrenceDate)).toEqual(["2026-03-31", "2026-05-31"]); });
  it("uses stable generated ids", () => { expect(expandSeriesForRange(routine(), "2026-06-08", "2026-06-09")[0].id).toBe(occurrenceId("series_test", "2026-06-08")); });
  it("cancels one occurrence", () => { const item = routine({ exceptions: [{ id: "x", occurrenceDate: "2026-06-15", type: "cancelled", createdAt: timestamp, updatedAt: timestamp }] }); expect(expandSeriesForRange(item, "2026-06-08", "2026-06-23").map((event) => event.occurrenceDate)).toEqual(["2026-06-08", "2026-06-22"]); });
  it("moves one occurrence", () => { const item = routine({ exceptions: [{ id: "x", occurrenceDate: "2026-06-15", type: "moved", movedToDate: "2026-06-16", movedToStartTime: "18:30", createdAt: timestamp, updatedAt: timestamp }] }); const moved = expandSeriesForRange(item, "2026-06-15", "2026-06-17")[0]; expect(moved.occurrenceDate).toBe("2026-06-15"); expect(moved.startAt).toContain("17:30:00.000Z"); });
  it("changes responsibility and car for one occurrence only", () => { const changed = routine({ exceptions: [{ id: "x", occurrenceDate: "2026-06-15", type: "changed", responsibleAdults: ["member_beck"], resourceNeeds: [], createdAt: timestamp, updatedAt: timestamp }] }); const events = expandSeriesForRange(changed, "2026-06-15", "2026-06-23"); expect(events[0].responsibleAdults).toEqual(["member_beck"]); expect(events[0].resourceNeeds).toEqual([]); expect(events[1].responsibleAdults).toEqual(["member_phil"]); expect(events[1].resourceNeeds).toHaveLength(1); });
  it("skips known closed term-time dates but keeps unknown dates", () => { const item = routine({ recurrence: { ...routine().recurrence, termTimeOnly: true } }); expect(expandSeriesForRange(item, "2026-06-15", "2026-06-16", { schoolCalendar: calendar })).toEqual([]); expect(expandSeriesForRange(item, "2026-07-27", "2026-07-28", { schoolCalendar: calendar })).toHaveLength(1); });
  it("creates fresh prep arrays without mutating series defaults", () => { const item = routine(); const events = expandSeriesForRange(item, "2026-06-08", "2026-06-23"); events[0].prepTasks[0].status = "done"; expect(events[1].prepTasks[0].status).toBe("open"); expect(item.defaultPrepTasks[0]).not.toHaveProperty("status"); });
  it("suppresses virtual duplicates when a materialised occurrence exists", () => { const event = { ...expandSeriesForRange(routine(), "2026-06-08", "2026-06-09")[0], id: "event_real" }; expect(expandSeriesForRange(routine(), "2026-06-08", "2026-06-09", { materialisedEvents: [event] })).toEqual([]); });
});
